service: movies
# app and org for use with dashboard.serverless.com
org: cazb999
app: movies
name: movies

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2

functions:
  crud:
    handler: app-lambda.handler
    events:
      - http:
          path: /api/movies
          method: get