version: 2.1
executors:
  node-docker:
    docker:
      - image: node
jobs:
  node-test:
    executor: node-docker
    steps:
      - run:
          name: instalación de paquetes
          command: npm install
      - run:
          name: Verificación de la correcta instalcion de paquetes
          command: checkout
      - run:
          name: Corriendo pruebas
          command: npm run test
workflows:
  node-tests:
    jobs:
      - node-test
