version: 2.1
executors:
  node-docker:
    docker:
      - image: node
jobs:
  node-build:
    executor: node-docker
    steps:
      - checkout
      - run:
          name: instalación de paquetes
          command: npm install
      - save_cache:
          name: Guardar carpeta node modules en cache
          key: mi-clave
          paths:
          - ./node_modules/
  node-test:
    executor: node-docker
    steps:
      - checkout
      - restore_cache:
           name: Restore carpeta node modules en cache
           keys:
             - mi-clave
      - run:
          name: Corriendo pruebas
          command: npm run test
          
orbs:
  serverless: circleci/serverless-framework@1.0.1
  aws-cli: circleci/aws-cli@0.1.22
workflows:
  node-tests:
    jobs:
      - node-build
      - node-test:
          requires:
            - node-build
