version: 2.1
executors:
  node-docker:
    docker:
      - image: node
jobs:
  node-build:
    executor: node-docker
    steps:
      - checkout
      - run:
          name: instalación de paquetes
          command: npm install
      - save_cache:
          name: Guardar carpeta node modules en cache
          key: mi-clave
          paths:
          - ./node_modules/
  node-test:
    executor: node-docker
    steps:
      - checkout
      - restore_cache:
           name: Restore carpeta node modules en cache
           keys:
             - mi-clave
      - run:
          name: Corriendo pruebas
          command: npm run test
  deploy-in-lambda:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: instalación de paquetes
          command: npm install
      - serverless/setup:
          provider: AWS
          app-name: movies
          org-name: cazb999
      - run:
          name: deploy
          command: serverless deploy -v
          
orbs:
  serverless: circleci/serverless-framework@1.0.1
  aws-cli: circleci/aws-cli@0.1.22
workflows:
  express-deploy-to-lambda:
    jobs:
      - node-build
      - node-test:
          requires:
            - node-build
      - deploy-in-lambda:
          requires:
            - node-test

